version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sum-api-sam-app"
s3_prefix = "sum-api-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
